### ISSUE TITLE
Add the ability to change ports

### ISSUE THREAD

**Issue by HarisSpahija** [HarisSpahija/tcgtrader-back-end#12]
In order to make the backend more customizeable. It would be a good issue to solve custom port changing. Somewhere in the code I should be able to give a parameter trough my .env file. This also requires a .env example!

**Comment by DavidCabal** [comment]
I'll fix this. Working on a pr now.

**Comment by HarisSpahija** [comment]
Good luck @DavidCabal !

**Comment by HarisSpahija** [comment]
Hey @DavidCabal , I added some comments on your pull request! Make sure that the .env is not in the repository, just a .env.example

**Comment by DavidCabal** [comment]
@HarisSpahija Gotcha, I'll update it now. I thought you wanted an actual .env in there for users to work off of. One moment...

**Comment by HarisSpahija** [comment]
resolves #13
