### ISSUE TITLE
Localhost cannot be found when there is no .env

### ISSUE THREAD

**Issue by HarisSpahija** [HarisSpahija/tcgtrader-back-end#14]
process.env.PORT gets passed and has a fallback of `8080`, but sometimes express will refuse to start because of `dotenv` missing in `require`.

**Issue to be solved**
`localhost:8080` should be able to be visited once `.env` file is missing

**Comment by mazma1** [comment]
Hi @HarisSpahija, I'll love to assist with this.

**Comment by chauhan-rakesh** [comment]
> process.env.PORT gets passed and has a fallback of `8080`, but sometimes express will refuse to start because of `dotenv` missing in `require`.
> 
> **Issue to be solved**
> `localhost:8080` should be able to be visited once `.env` file is missing

hi. @HarisSpahija, I w'll help it to get resolved.
