### ISSUE TITLE
Add domain model to readme

### ISSUE THREAD

**Issue by Marthijs-Berfelo** [HarisSpahija/tcgtrader-back-end#21]
As discussed, the new domain model:

![trading-card-games_domain](https://user-images.githubusercontent.com/42251286/67411635-39926e80-f5be-11e9-8d84-a9b3f0bc4fd2.png)

**Comment by HarisSpahija** [comment]
Thanks for the issue, I will open to Hacktoberfest. If anyone is interested in solving this!

**Comment by Anilpandiya** [comment]
@Marthijs-Berfelo can you please tell the exact position where you need the domain model to be placed in readme file ?

**Comment by m-murasovs** [comment]
I'd like to claim this one if it's still going :)

**Comment by HarisSpahija** [comment]
@Anilpandiya If you could add a new header to the README titled Domain Model with the image underneath it, would be great 😄 

Underneath the Resolvers title should be sufficiant

**Comment by Anilpandiya** [comment]
added domain model. PR raised.
